language: node_js
node_js:
  - "10"

cache:
  directories:
    - lambda/node_modules
install:
  - npm install -g bespoken-tools
  - cd alexa-skill/lambda/ && npm install
  - cd ..
script:
  - bst test
