language: node_js
node_js:
  - "10"

cache:
  directories:
    - lambda/custom/node_modules
install:
  - npm install -g bespoken-tools
  - npm install codecov -g
  - cd alexa-skill/lambda/custom && npm install
  - cd ../..
script:
  - bst test
  - codecov
